/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialog: typeof import('naive-ui')['NDialog']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NRow: typeof import('naive-ui')['NRow']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NAlert: typeof import('naive-ui')['NAlert']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NCol: typeof import('naive-ui')['NCol']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialog: typeof import('naive-ui')['NDialog']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NInput: typeof import('naive-ui')['NInput']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModal: typeof import('naive-ui')['NModal']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NProgress: typeof import('naive-ui')['NProgress']
  const NResult: typeof import('naive-ui')['NResult']
  const NRow: typeof import('naive-ui')['NRow']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NStatistic: typeof import('naive-ui')['NStatistic']
  const NSwitch: typeof import('naive-ui')['NSwitch']
  const NTag: typeof import('naive-ui')['NTag']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const NTree: typeof import('naive-ui')['NTree']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}