/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppError: typeof import('./components/App/Error.vue')['default']
    AppNavbar: typeof import('./components/App/Navbar.vue')['default']
    G2MHeader: typeof import('./components/G2M/Header.vue')['default']
    GameAddDialog: typeof import('./components/Game/AddDialog.vue')['default']
    GameDownloadDialog: typeof import('./components/Game/DownloadDialog.vue')['default']
    GameEditDialog: typeof import('./components/Game/EditDialog.vue')['default']
    GameExtractDialog: typeof import('./components/Game/ExtractDialog.vue')['default']
    GameInfoModInstaller: typeof import('./components/Game/Info/ModInstaller.vue')['default']
    GameInfoTab1: typeof import('./components/Game/Info/Tab1.vue')['default']
    GameInfoTab2: typeof import('./components/Game/Info/Tab2.vue')['default']
    GameInfoTab3: typeof import('./components/Game/Info/Tab3.vue')['default']
    GameList: typeof import('./components/Game/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
